// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGth0JOIk4OZk6xL_wqqJSVjl138LBHaM',
    appId: '1:835080242367:web:a008bc2d2d470b947a320a',
    messagingSenderId: '835080242367',
    projectId: 'mobile-shop-database',
    authDomain: 'mobile-shop-database.firebaseapp.com',
    storageBucket: 'mobile-shop-database.firebasestorage.app',
    measurementId: 'G-MBGK7LYHFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxTLvPEDjoxYkxZmdNb7geWHL6B5Usc4',
    appId: '1:835080242367:android:a0348bd60397ca837a320a',
    messagingSenderId: '835080242367',
    projectId: 'mobile-shop-database',
    storageBucket: 'mobile-shop-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90iGPmEH_tzudwjxnRPAhY5sJSLrpA-E',
    appId: '1:835080242367:ios:f7ddce3d95f8fba87a320a',
    messagingSenderId: '835080242367',
    projectId: 'mobile-shop-database',
    storageBucket: 'mobile-shop-database.firebasestorage.app',
    iosBundleId: 'com.example.mobileShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA90iGPmEH_tzudwjxnRPAhY5sJSLrpA-E',
    appId: '1:835080242367:ios:f7ddce3d95f8fba87a320a',
    messagingSenderId: '835080242367',
    projectId: 'mobile-shop-database',
    storageBucket: 'mobile-shop-database.firebasestorage.app',
    iosBundleId: 'com.example.mobileShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGth0JOIk4OZk6xL_wqqJSVjl138LBHaM',
    appId: '1:835080242367:web:f2441701e72fbfcc7a320a',
    messagingSenderId: '835080242367',
    projectId: 'mobile-shop-database',
    authDomain: 'mobile-shop-database.firebaseapp.com',
    storageBucket: 'mobile-shop-database.firebasestorage.app',
    measurementId: 'G-W0JP2KHZPT',
  );
}
